/**
 * Canonical identity contracts for Baobab.
 *
 * Baobab uses a two-layer identity model for both users and relations.
 * These contracts make each layer explicit and prevent cross-layer confusion.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * USER IDENTITY
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * internalAuthUserId (InternalAuthUserId)
 *   The Supabase auth UUID (auth.uid()). Private. Backend-internal only.
 *   Stored as side_a_user_id / side_b_user_id in shared_relationship_reveals.
 *   Never exposed in QR cards, deep links, or any public product surface.
 *
 * publicProfileId (PublicProfileId)
 *   A stable, shareable identifier for QR cards, invite lookup, and future
 *   social graph features. Explicitly distinct from the auth UUID.
 *   Provisioned at app bootstrap via get_or_create_public_profile_id() RPC.
 *   Do not substitute internalAuthUserId here even temporarily.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * RELATION IDENTITY
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * localDraftId (LocalDraftId)
 *   Device-local opaque identifier. Used for navigation params, AsyncStorage
 *   keying, and store lookups. Non-canonical. Not shared cross-user or cross-device.
 *   Stored in Relation.id. Generated by newLocalDraftId().
 *   Must never be sent to the backend as a relation join key.
 *
 * canonicalRelationId (CanonicalRelationId)
 *   A stable UUID assigned when a local relation is promoted to shared —
 *   specifically at invite creation time.
 *   This is the only valid cross-user / cross-device join key for a relation.
 *   Stored in Relation.canonicalRelationId. Null for purely local relations.
 *   Generated client-side via newCanonicalRelationId() and sent to the backend
 *   as relationship_id. The backend column is text; only UUID-only values are
 *   sent from this point forward. A text→uuid column migration is a separate stage.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * INVARIANTS
 * ─────────────────────────────────────────────────────────────────────────────
 *   - Never send Relation.id (localDraftId) to the backend as a relation key.
 *   - Never expose internalAuthUserId in QR cards, deep links, or public flows.
 *   - Never infer publicProfileId from internalAuthUserId without explicit provisioning.
 *   - Relation.canonicalRelationId is null until a relation has been promoted to shared.
 *   - Never send Relation.id (localDraftId) to the backend as relationship_id.
 *   - Always call newCanonicalRelationId() and persist via setCanonicalRelationId()
 *     before the first invite creation for any relation.
 *   - Relation.sourceCardMeId stores the scanned user's publicProfileId (v2 QR)
 *     or their legacy me.id local alias (v1 QR). Treat v1 values as opaque strings —
 *     never query the backend using a v1 sourceCardMeId as a user lookup key.
 */

// ── User identity ─────────────────────────────────────────────────────────────

/**
 * The Supabase auth UUID (auth.uid()).
 * Private, backend-internal. Must never be exposed publicly.
 */
export type InternalAuthUserId = string;

/**
 * A stable, shareable public profile identifier.
 * Intended for QR cards, scan deduplication, and future social lookup.
 * Currently not provisioned — null in MeProfile until the provisioning stage.
 * Never substitute InternalAuthUserId for this type.
 */
export type PublicProfileId = string;

// ── Relation identity ─────────────────────────────────────────────────────────

/**
 * Device-local opaque identifier for a draft relation.
 * Used for navigation params, AsyncStorage keying, and store lookups.
 * Non-canonical. Must never be used as a backend relation join key.
 * Held in Relation.id. Generated by newLocalDraftId().
 */
export type LocalDraftId = string;

/**
 * Stable UUID identifying a relation promoted to shared.
 * Assigned at invite creation time and mirrored from the backend record.
 * The canonical cross-user / cross-device join key for a relation.
 * Held in Relation.canonicalRelationId. Null for local-only relations.
 */
export type CanonicalRelationId = string;

// ── Generators ────────────────────────────────────────────────────────────────

/**
 * Generates a new canonical relation ID for a relation being promoted to shared.
 *
 * Call this exactly once per relation, at invite creation time, when
 * Relation.canonicalRelationId is null. Persist the result immediately via
 * store.setCanonicalRelationId() before sending it to the backend.
 *
 * This UUID becomes the cross-user / cross-device join key for the relation
 * and the relationship_id stored in shared_relationship_reveals.
 */
export function newCanonicalRelationId(): CanonicalRelationId {
  return generateUUID();
}

/**
 * Generates a new local draft ID for a relation.
 *
 * Format: "local-<uuid>" — the "local-" prefix makes the non-canonical,
 * device-local nature of this ID explicit and guarded by isLocalDraftId().
 *
 * NOT YET WIRED INTO PRODUCTION FLOWS.
 * The store currently still uses r-${Date.now()} for Relation.id because
 * that value can still reach the backend as relationship_id during invite creation.
 * This generator will replace it once canonicalRelationId is properly separated
 * from Relation.id in the invite flow (canonical relation creation stage).
 */
export function newLocalDraftId(): LocalDraftId {
  return `local-${generateUUID()}`;
}

/**
 * Returns true if the given relation ID is a local draft (not a canonical relation ID).
 * Use this to guard against accidentally sending a local ID to the backend as a join key.
 *
 * Recognizes both the new "local-<uuid>" format and the legacy "r-<timestamp>" format.
 */
export function isLocalDraftId(id: string): boolean {
  return id.startsWith('local-') || id.startsWith('r-');
}

// ── Internal UUID generator ───────────────────────────────────────────────────

function generateUUID(): string {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }
  // Minimal RFC 4122 v4 fallback. Not expected to run on production iOS,
  // which always has crypto.randomUUID available.
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    return (c === 'x' ? r : (r & 0x3) | 0x8).toString(16);
  });
}
